### PR TITLE
Update status of FLIP 120

### PR DESCRIPTION
**Pull request by tarakby**
update status to implemented

### CODE REVIEW

**Comment by KshitijChaudhary666** [comment]
Hi @tarakby - this FLIP is not reflected on FLIP project tracker. Did you follow the process outlined in https://github.com/onflow/flips? Specifically please remember to do the following without which the FLIP won't get visibility on the project tracker -->

Create an [issue](https://github.com/onflow/flips/issues/new/choose) by using one of the FLIP issue templates based on the type of the FLIP - application, governance, cadence or protocol. The title of the issue should be the title of your FLIP, e.g., "Dynamic Inclusion fees". Submit the issue. Note the issue number that gets assigned. 
Then, Create your FLIP as a pull request to this repository ([onflow/flips](https://github.com/onflow/flips)). Use the issue number generated in step 2 as the FLIP number. And mention the FLIP issue by copying the GitHub URL or the issue in the comment section.

**Comment by KshitijChaudhary666** [comment]
> Hey @KshitijChaudhary666, thanks for pointing the FLIP process steps.
> 
> I believe the FLIP process got updated after I created FLIP 120. You can notice the [FLIP PR](https://github.com/onflow/flips/pull/120) started on July 13, and at that time the FLIP number would be the PR number. The extra step 2 of going through creating an issue [was added](https://github.com/onflow/flips/commit/00a9ecf01a45478b56617305af10000b3a7f43d4) on August 23.
> 
> Btw the same happened for [FLIP 123](https://github.com/onflow/flips/pull/123). I hope it's possible to manually fix the tracker for both.

Hey! Got it - thanks for sharing the details. Could you pls create two issues (for each flip) in the new format and mark the right "type" (Cadence) and "status" (implemented?) and that should bring them to the project tracker. Thanks, really appreciate it!

**Comment by tarakby** [comment]
If I create 2 issues, the FLIPs won't have the issues numbers because they were already merged long time ago (and we always referred to them as 120 and 123). Wouldn't that mess with the tracker?

**Comment by tarakby** [comment]
here is the issue https://github.com/onflow/flips/issues/260. 

Feel free to merge or close the current PR.

**Review by turbolent — APPROVED** [review]

**Pull request merged**
