### PR TITLE
FLIP-660: Readability cleanups

### PR DESCRIPTION
**Pull request by SaveTheRbtz**
## Description
In this PR:
* Cleanup english.  I can't write english myself, so I've asked GPT-3 to "Rewrite the following paragraphs like a technical magazine editor, correcting spelling, idioms, punctuation, and word choices as necessary".
* Make $\LaTeX$ readable.  Mostly a machine-rewrite with:
```python
def repl(m: re.Match) -> str:
     return '$' + urllib.parse.unquote(m.group(1)) + '$'
re.sub(r'<img src="https://render.githubusercontent.com/render/math?math=([^"]+)">', repl, s)
```

Ref: https://github.com/onflow/flow/pull/660
Ref: https://github.com/onflow/flow/pull/1147

### CODE REVIEW

**Comment by janezpodhostnik** [comment]
Thank you for this! Nice tool for the toolbox!

As for the Latex, I think I had problems last time with the github dark theme with just using the github math, but that no longer seems to be a problem.

**Review by janezpodhostnik — APPROVED** [review]

**Review by Tonix517 — APPROVED** [review]

**Comment by SaveTheRbtz** [comment]
bors merge

**Comment by AlexHentschel** [comment]
very cool. Love the Latex embedding!

**Comment by Tonix517** [comment]
cool beans. not directly related, how can we also integrate terminology polishing, like this https://github.com/onflow/flips/pull/14?

**Pull request merged**
